# -*- coding: utf-8 -*-

{
    'name': "Aspire Recruitment Extension",
    'version': '15.0.0.0.23',
    'description': "Using this module user able to filter applications from the Candidates.",
    'author': 'Aspire Softserv Private Limited',
    'website': "https://aspiresoftware.in",
    'summary': '',
    'category': 'Human Resources',
    'depends': ['hr', 'hr_recruitment', 'contacts',
                'calendar',
                'fetchmail',
                'utm',
                'attachment_indexation',
                'web_tour',
                'hr_skills',
                'base',
                'base_automation',
                'mail',
                'website',
                'web',
                ],

    'data': [
        'security/hr_security.xml',
        'security/ir.model.access.csv',
        #'data/hr_recruitment_degree_data.xml',
        'data/hr_recruitment_data.xml',
        #'data/hr_multicompany_data.xml',
        'data/hr_que_stages_data.xml',
        'data/activity_type_data.xml',
        'data/candidate_onboarding_mail.xml',
        #'data/ht_applicant_category_data.xml',
        'data/skills_data.xml',
        'wizard/hr_questions_wiz_views.xml',
        'wizard/send_interview_wiz_view.xml',
        'wizard/job_opening_report_views.xml',
        'wizard/transfer_to_application_views.xml',
        'wizard/refer_to_job_opening_view.xml',
        'wizard/merge_skills.xml',
        'wizard/candidate_onboarding.xml',
        'report/applicants_per_hire_reports.xml',
        'report/interviewer_report.xml',
        'report/vacancies_vs_filled_reports.xml',
        'report/time_to_hire_reports.xml',
        'report/offer_acc_per_hire_reports.xml',
        'report/candidate_exp_reports.xml',
        'report/application_report.xml',
        'views/candidates_view.xml',
        'views/job_opening_view.xml',
        'views/job_opening_report_template_views.xml',
        'views/hr_recruitment_views.xml',
        'views/hr_questions_views.xml',
        'views/applicant_feedback_que_views.xml',
        'views/candidate_blocked_email.xml',
        'views/multiple_candidate_email_view.xml',
        'views/applicant_tracking_views.xml',
        'views/current_company_views.xml',
        'views/opening_kickoff.xml',
        'views/interviewer_report.xml',
        'views/hr_skill_type.xml',
        'views/candidate_onboarding.xml'
    ],
    'assets': {
        'web.assets_backend': [
            ('aspl_hr_recruitment/static/description/src/js/ribbon.js'),
        ],
    },
    'external_dependencies': {'python': ['bs4', 'xlsxwriter']},
    'installable': True,
    'sequence': -99,
    'application': True,
    'license': 'LGPL-3',
    'auto_install': False
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
