class Constant:
    # hr_employee.py constant
    INVALID_NOMINATION_PHONE = 'Error! Enter only 10 digit number in nomination "Phone"'
    INVALID_NOMINATION_MOBILE = 'Error! Enter only 10 digit number in nomination "Mobile Phone" '
    INVALID_NOMINATION_EMAIL = 'Error! Enter valid email address in nomination "Email"'
    INVALID_EMPLOYEE_NAME = 'Error! Enter only alphabets in employee "Name"'
    INVALID_MOBILE_NO = 'Error! Enter only 10 digit number in "Mobile Phone"'
    INVALID_WORK_PHONE = 'Error! Enter only 10 digit number in "Work Phone"'
    INVALID_WORK_EMAIL = 'Error! Enter valid email address in "Work Email"'
    INVALID_PERSONAL_EMAIL = 'Error! Enter valid email address in "Personal Email"'
    INVALID_FATHER_NAME = 'Error! Enter only alphabets in "Father Name"'
    INVALID_SPOUSE_NAME = 'Error! Enter only alphabets in "Spouse Name"'
    INVALID_DATE = 'Error! "Confirm Date" must be greater than "Join Date"'
    INVALID_PROBATION_PERIOD = 'Error! Enter "Probation Period" in month'
    INVALID_NOTICE_PERIOD = 'Error! Enter "Notice Period" in month'
    INVALID_TRAINING_PERIOD = 'Error! Enter "Training Period" in month'
    # INVALID_BANK_NAME = 'Error! Enter only alphabets in employee "Bank Name"'
    INVALID_UAN_NO = 'Error! Enter "UAN NUMBER" less than 12 digits'
    INVALID_PHONE1 = 'Error! Enter only 10 digit number in present address "Mobile No"'
    INVALID_PHONE2 = 'Error! Enter only 10 digit number in present address "Phone No"'
    INVALID_PER_PHONE1 = 'Error! Enter only 10 digit number in permanent address "Mobile No"'
    INVALID_PER_PHONE2 = 'Error! Enter only 10 digit number in permanent address "Phone No"'
    INVALID_PCODE1 = 'Error! Enter only digits in present address "Pin Code"'
    INVALID_PCODE2 = 'Error! Enter only digits in permanent address "Pin Code"'
    INVALID_BANK_ACC = 'Error! Enter only digits in "Bank Account Number"'
    INVALID_POSITATION_DATE = 'Error! "End Date" must be greater than "Start Date"'
    INVALID_PF_NUMBER = 'Error! Enter proper "PF NUMBER"'
    INVALID_EMERGENCY_CONTACT = 'Error! Enter only 10 digit number in emergency info "Contact No"'

    # employee_family.py constant
    INVALID_MEMBER_NAME = 'Error! Enter only alphabets in family member "Name"'
    INVALID_MEMBER_PINCODE = 'Error! Enter only digits in family member address "Pin Code"'
    INVALID_MEMBER_PHONE = 'Error! Enter only 10 digit number in family member "Mobile Phone"'
    INVALID_RELATION_NAME = 'Error! Enter only alphabets in "Relation Name"'

    # employee_identity.py constant
    REQUIRED_AADHAAR_NO = 'Enter "Aadhaar Number" must be required'
    INVALID_AADHAAR_NO = 'Enter only digits in "Aadhaar Number"'
    REQUIRED_AADHAAR_NAME = 'Enter "Aadhaar Name" must be required'
    INVALID_AADHAAR_NAME = 'Enter only alphabets in "Aadhaar Name"'
    REQUIRED_EC_NO = 'Enter "EC Number" must be required'
    REQUIRED_EC_NAME = 'Enter "Ec Name" must be required'
    INVALID_EC_NAME = 'Enter only alphabets in "EC Name"'
    REQUIRED_PASSPORT_NO = 'Enter "Passport Number" must be required'
    REQUIRED_PASSPORT_NAME = 'Enter "Passport Name" must be required'
    # INVALID_PASSPORT_NAME = 'Enter only alphabets in "Passport Name"'
    REQUIRED_EXPIRE_DATE = 'Enter "Expiry Date must be required"'
    REQUIRED_PAN_NO = 'Enter "PAN Number" must be required'
    REQUIRED_PAN_NAME = 'Enter "PAN Name" must be required'
    REQUIRED_BANK_ACC_NO = 'Enter "Bank Account Number" must be required"'
    INVALID_BANK_ACC_NO = 'Enter only digits in "Bank Account Number"'
    REQUIRED_IFSC_CODE = 'Enter "IFSC Code" must be required'
    REQUIRED_BANK_NAME = 'Enter "Name in bank" must be required'
    INVALID_BANK_NAME = 'Enter only alphabets in "Name in Bank"'
    REQUIRED_LICENSE_NO = 'Enter "Licence Number" must be required'
    REQUIRED_LICENSE_NAME = 'Enter "License Name" must be required'
    INVALID_LICENSE_NAME = 'Enter only alphabets in "License Name"'

    # hr_bank_detial.py constant
    INVALID_PCODE = 'Error! Enter only digits in "Pin Code"'
    INVALID_MOBILE_PHONE = 'Error! Enter only 10 digit number in "Mobile Phone"'

    # passport_visa.py constant
    INVALID_PASSPORT_NAME = 'Passport "First Name" can only contain alphabet.'
    INVALID_PASSPORT_SUR_NAME = 'Passport "Last Name" can only contain alphabet.'
    INVALID_MIDDLE_NAME = 'Passport "Middle Name" can only contain alphabet.'
    INVALID_CURRENTLY_WITH = '"Currently With" can only contain alphabet.'
    INVALID_VISA_NAME = 'Visa "Name" can only contain alphabet.'
    INVALID_PASSPORT_NUMBER = 'Error! Enter VALID Passport Number in "Passport No".'

    # position_history.py constant
    INVALID_DESIGNATION_DATE = '"Effective To" must be greater than "Effective From" in designation history'
    INVALID_LOCATION_DATE = '"Effective To" must be greater than "Effective From" in location history'
    INVALID_DEPARTMENT_DATE = '"Effective To" must be greater than "Effective From" in department history'
    INVALID_GRADE_DATE = '"Effective To" must be greater than "Effective From" in grade history'
    INVALID_DIVISION_DATE = '"Effective To" must be greater than "Effective From" in division history'
    INVALID_COST_DATE = '"Effective To" must be greater than "Effective From" in cost history'
    INVALID_REPORTING_DATE = '"Effective To" must be greater than "Effective From" in reporting history'
    INVALID_COMPANY_DATE = 'Effective To" must be greater than "Effective From" in company history'

    # passport size photo extension check
    INVALID_FILE_TYPE = 'Effective To" must be greater than "Effective From" in company history'
